version: '3.8'

services:
  api:
    build: .
    container_name: crm_api
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=crm_db
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    command: yarn dev
    volumes:
      - .:/app
    working_dir: /app

  db:
    image: mysql:8.0
    container_name: crm_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crm_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: crm_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
